info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T02:26:39.571Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\FundoNote\\fundo-app\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12\n    at database (C:\\FundoNote\\fundo-app\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\src\\/index.js:30:9)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Module._compile (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Object.newLoader [as .js] (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:922:12)\n    at Function.runMain (node:internal/modules/run_main:81:12)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\node\\src\\_babel-node.ts:223:12)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:922:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-02-17T02:27:09.592Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T02:28:08.909Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\FundoNote\\fundo-app\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12","timestamp":"2023-02-17T02:28:38.921Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T02:30:22.418Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\FundoNote\\fundo-app\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12","timestamp":"2023-02-17T02:30:52.430Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T02:36:45.464Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\FundoNote\\fundo-app\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12","timestamp":"2023-02-17T02:37:15.470Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:38:04.826Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\FundoNote\\fundo-app\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12","timestamp":"2023-02-17T02:38:34.849Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:40:10.576Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:40:10.593Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:47:12.626Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:47:12.641Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:49:42.984Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:49:42.998Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:50:21.797Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:50:21.813Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:50:39.588Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:50:39.602Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:51:56.734Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:51:56.757Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:53:04.358Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:53:04.385Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:55:06.217Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:55:06.231Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:57:03.242Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:57:03.256Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:57:26.848Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:57:26.863Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:59:01.285Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:59:01.300Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of null (reading 'password')
    at _callee2$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:33:49)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T02:59:06.800Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:59:53.985Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:59:54.004Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T03:00:19.704Z"}
info: Connected to the database. {"timestamp":"2023-02-17T03:00:19.721Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T03:00:34.292Z"}
info: Connected to the database. {"timestamp":"2023-02-17T03:00:34.307Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of null (reading 'password')
    at _callee2$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:33:49)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T03:00:47.550Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T03:01:16.525Z"}
info: Connected to the database. {"timestamp":"2023-02-17T03:01:16.540Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T03:24:26.075Z"}
info: Connected to the database. {"timestamp":"2023-02-17T03:24:26.128Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T03:42:59.784Z"}
info: Connected to the database. {"timestamp":"2023-02-17T03:42:59.834Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T04:01:37.255Z"}
info: Connected to the database. {"timestamp":"2023-02-17T04:01:37.273Z"}
info: Connected to the database. {"timestamp":"2023-02-17T05:45:29.832Z"}
info: Connected to the database. {"timestamp":"2023-02-17T05:46:09.650Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T05:46:58.839Z"}
info: Connected to the database. {"timestamp":"2023-02-17T05:46:58.872Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T05:50:14.991Z"}
info: Connected to the database. {"timestamp":"2023-02-17T05:50:15.038Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T05:50:20.150Z"}
info: Connected to the database. {"timestamp":"2023-02-17T05:50:20.166Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T05:50:25.918Z"}
info: Connected to the database. {"timestamp":"2023-02-17T05:50:25.934Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T05:50:31.827Z"}
info: Connected to the database. {"timestamp":"2023-02-17T05:50:31.841Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T05:50:37.335Z"}
info: Connected to the database. {"timestamp":"2023-02-17T05:50:37.351Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T05:50:43.078Z"}
info: Connected to the database. {"timestamp":"2023-02-17T05:50:43.093Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T05:50:48.485Z"}
info: Connected to the database. {"timestamp":"2023-02-17T05:50:48.502Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T06:04:15.638Z"}
info: Connected to the database. {"timestamp":"2023-02-17T06:04:15.655Z"}
error: 
    status - 500 
    message - ValidationError: "email" must be a valid email 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T06:05:16.330Z"}
error: 
    status - 500 
    message - ValidationError: "email" must be a valid email 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T06:05:26.675Z"}
error: 
    status - 500 
    message - ValidationError: "email" must be a valid email 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T06:05:37.354Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T06:10:03.375Z"}
info: Connected to the database. {"timestamp":"2023-02-17T06:10:03.390Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T06:14:14.820Z"}
info: Connected to the database. {"timestamp":"2023-02-17T06:14:14.835Z"}
info: Connected to the database. {"timestamp":"2023-02-17T06:15:13.167Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T06:16:27.838Z"}
info: Connected to the database. {"timestamp":"2023-02-17T06:16:27.855Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T09:40:12.195Z"}
info: Connected to the database. {"timestamp":"2023-02-17T09:40:12.251Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" must be a string 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T09:41:08.103Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T09:45:54.784Z"}
info: Connected to the database. {"timestamp":"2023-02-17T09:45:54.833Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T09:47:35.957Z"}
info: Connected to the database. {"timestamp":"2023-02-17T09:47:35.999Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" with value "ab" fails to match the required pattern: /^[a-zA-Z]{3,30}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T09:47:48.799Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" with value "ab1" fails to match the required pattern: /^[a-zA-Z]{3,30}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T09:47:59.284Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" with value "ab541" fails to match the required pattern: /^[a-zA-Z]{3,30}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T09:48:07.753Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" with value "abssssssssssssssssssssssssssssssssssss" fails to match the required pattern: /^[a-zA-Z]{3,30}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T09:48:58.837Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T09:50:46.440Z"}
info: Connected to the database. {"timestamp":"2023-02-17T09:50:46.489Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T09:56:37.567Z"}
info: Connected to the database. {"timestamp":"2023-02-17T09:56:37.606Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.string(...).minOfSpecialCharacters is not a function
    at newUserValidator (C:\FundoNote\fundo-app\src\validators\/user.validator.js:8:28)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T09:57:51.822Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.string(...).minOfSpecialCharacters is not a function
    at newUserValidator (C:\FundoNote\fundo-app\src\validators\/user.validator.js:8:28)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T09:58:26.350Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:00:07.692Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:00:07.732Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.string(...).minOfSpecialCharacters is not a function
    at newUserValidator (C:\FundoNote\fundo-app\src\validators\/user.validator.js:8:28)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:00:19.841Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:07:52.883Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:07:52.912Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:09:46.761Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:09:46.776Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "12345687" fails to match the required pattern: /^[a-z]{3}-[A-Z]{1}-[0-9]{3}-[!@#$%&*]{1}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:09:54.663Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "Asdf@123" fails to match the required pattern: /^[a-z]{3}-[A-Z]{1}-[0-9]{3}-[!@#$%&*]{1}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:10:27.975Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "Asdf123@" fails to match the required pattern: /^[a-z]{3}-[A-Z]{1}-[0-9]{3}-[!@#$%&*]{1}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:11:05.762Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:11:33.756Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:11:33.774Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "Asdf123@" fails to match the required pattern: /^[a-z+]{3}-[A-Z+]{1}-[0-9+]{3}-[!@#$%&*]{1}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:11:37.020Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:14:23.589Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:14:23.605Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "Asdf123@" fails to match the required pattern: /^[a-z]{3,}-[A-Z+]{1,}-[0-9+]{3,}-[!@#$%&*]{1,}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:14:30.786Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asdfghvb" fails to match the required pattern: /^[a-z]{3,}-[A-Z+]{1,}-[0-9+]{3,}-[!@#$%&*]{1,}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:14:54.443Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:16:04.667Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:16:04.683Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asdfghvb" fails to match the required pattern: /^[a-z]{3,}-[A-Z+]{1,}-[0-9+]{3,}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:16:11.095Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "Asdf123" fails to match the required pattern: /^[a-z]{3,}-[A-Z+]{1,}-[0-9+]{3,}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:16:33.160Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:19:29.661Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:19:29.677Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "Asdf123" fails to match the required pattern: /^[a-z]{3,}-[A-Z]{1,}-[0-9]{3,}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:19:37.683Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:19:55.784Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:19:55.800Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "Asdf123" fails to match the required pattern: /^[a-z]{3}-[A-Z]{1}-[0-9]{3}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:19:58.772Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:20:31.717Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:20:31.734Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "Asdf123" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:20:44.202Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:21:23.270Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:21:23.286Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:22:16.107Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:22:16.124Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:22:32.108Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:22:32.128Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:23:28.549Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:23:28.566Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T11:13:16.118Z"}
info: Connected to the database. {"timestamp":"2023-02-17T11:13:16.134Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T11:22:26.144Z"}
info: Connected to the database. {"timestamp":"2023-02-17T11:22:26.160Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T11:24:05.366Z"}
info: Connected to the database. {"timestamp":"2023-02-17T11:24:05.383Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asderf" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T11:24:22.360Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asderdddf" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T11:24:27.523Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asderdddf1" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T11:24:35.052Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "Asderdddf1" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T11:24:41.922Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asdfgh" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T11:24:56.655Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asdfgh@" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T11:25:11.576Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asdfgh@12" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T11:25:17.922Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T11:25:45.834Z"}
info: Connected to the database. {"timestamp":"2023-02-17T11:25:45.890Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asdfg" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T11:27:30.524Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T13:33:13.202Z"}
info: Connected to the database. {"timestamp":"2023-02-17T13:33:13.227Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T13:33:41.063Z"}
info: Connected to the database. {"timestamp":"2023-02-17T13:33:41.079Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T14:03:58.592Z"}
info: Connected to the database. {"timestamp":"2023-02-17T14:03:58.663Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "qweasdzxc" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T14:04:50.855Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "qweasdzxc4" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T14:05:19.793Z"}
error: 
    status - 500 
    message - ReferenceError: userSchema is not defined
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:5:3)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.newRegistration (C:\FundoNote\fundo-app\src\services\/user.service.js:4:29)
    at _callee$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:12:36)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at newRegistration (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:10:29)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at newUserValidator (C:\FundoNote\fundo-app\src\validators\/user.validator.js:14:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T14:05:33.330Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T14:06:41.001Z"}
info: Connected to the database. {"timestamp":"2023-02-17T14:06:41.058Z"}
error: 
    status - 500 
    message - ReferenceError: userSchema is not defined
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:6:3)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.newRegistration (C:\FundoNote\fundo-app\src\services\/user.service.js:5:29)
    at _callee$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:12:36)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at newRegistration (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:10:29)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at newUserValidator (C:\FundoNote\fundo-app\src\validators\/user.validator.js:14:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T14:06:47.475Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T14:11:38.387Z"}
info: Connected to the database. {"timestamp":"2023-02-17T14:11:38.430Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T14:13:08.909Z"}
info: Connected to the database. {"timestamp":"2023-02-17T14:13:08.985Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T14:13:40.071Z"}
info: Connected to the database. {"timestamp":"2023-02-17T14:13:40.121Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:16:23.890Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:16:23.905Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:16:55.405Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:16:55.423Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:17:55.480Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:17:55.499Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:17:59.730Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:17:59.745Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:30:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:18:22.275Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:19:36.788Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:19:36.805Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token } in JSON at position 46
    at JSON.parse (<anonymous>)
    at parse (C:\FundoNote\fundo-app\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:20:09.603Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:18:30)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:20:15.459Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected string in JSON at position 39
    at JSON.parse (<anonymous>)
    at parse (C:\FundoNote\fundo-app\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:20:26.499Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:21:48.657Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:21:48.674Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:22:01.642Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:23:58.101Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:25:24.791Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:25:44.215Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:25:44.233Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:25:52.485Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:31:53.947Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:31:53.962Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:31:56.168Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:33:07.063Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:33:07.079Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:33:22.850Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:36:39.221Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:36:39.235Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:36:45.548Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:40:46.277Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:40:46.295Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:30:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:41:02.827Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:43:40.120Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:43:40.137Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:47:33.968Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:47:33.985Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:48:08.668Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:48:08.686Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:29:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:48:12.004Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of null (reading 'password')
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:59)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:48:22.475Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of null (reading 'password')
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:59)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:48:35.310Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:29:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:48:41.014Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:54:37.668Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:54:37.685Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:55:11.115Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:55:11.133Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:31)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:55:26.206Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:14:45.607Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:14:45.629Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:31)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:14:48.756Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:31)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:14:55.955Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:31)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:22:57.835Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:24:36.140Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:24:36.158Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:31)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:24:39.259Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:26:42.731Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:26:42.750Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:24:31)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:26:47.148Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:24:31)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:34:53.943Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:38:31.332Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:38:31.350Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:24:31)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:39:04.430Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:41:51.331Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:41:51.350Z"}
error: 
    status - 500 
    message - ReferenceError: req is not defined
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:27:41)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:41:56.447Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:43:21.470Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:43:21.491Z"}
error: 
    status - 500 
    message - TypeError: _user.default.getUser is not a function
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:27:33)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:43:30.881Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:43:49.666Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:43:49.688Z"}
error: 
    status - 500 
    message - TypeError: _user.default.userLogin is not a function
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:27:33)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:43:52.726Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:44:48.994Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:44:49.014Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:45:31.323Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:45:31.341Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:47:36.547Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:47:36.574Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:31)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:47:44.200Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:48:01.177Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:48:01.200Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:16:03.080Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:16:03.100Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:16:07.098Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:16:07.180Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:16:17.818Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:16:17.837Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:16:20.705Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:16:20.721Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:16:26.507Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:16:26.524Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:17:55.418Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:17:55.439Z"}
error: 
    status - 500 
    message - Error: incorrect password 
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:25:15)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T17:18:08.484Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'password')
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:62)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T17:18:17.250Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'password')
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:62)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T17:18:30.815Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:19:03.955Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:19:03.974Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:28:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T17:19:19.058Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'password')
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:62)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T17:19:25.541Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:20:02.160Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:20:02.177Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:28:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T17:20:14.057Z"}
error: 
    status - 500 
    message - Error: incorrect password 
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:25:15)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T17:20:22.633Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:20:34.078Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:20:34.097Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:21:46.215Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:21:46.237Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:22:03.360Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:22:03.380Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:23:23.206Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:23:23.221Z"}
