error: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1733:16)
    at listenInCluster (node:net:1781:12)
    at Server.listen (node:net:1869:7)
    at Function.listen (C:\FundoNote\fundo-app\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (C:\FundoNote\fundo-app\src\/index.js:37:5)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._compile (C:\FundoNote\fundo-app\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.newLoader [as .js] (C:\FundoNote\fundo-app\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.runMain (node:internal/modules/run_main:81:12)
    at Object.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\node\src\_babel-node.ts:223:12)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {"date":"Thu Feb 16 2023 16:24:46 GMT+0530 (India Standard Time)","error":{"address":"::","code":"EADDRINUSE","errno":-4091,"port":3000,"syscall":"listen"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":30311.328},"process":{"argv":["node","C:\\FundoNote\\fundo-app\\src\\index.js"],"cwd":"C:\\FundoNote\\fundo-app","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18995709,"external":20531074,"heapTotal":92237824,"heapUsed":58903344,"rss":134459392},"pid":7712,"uid":null,"version":"v18.13.0"},"stack":"Error: listen EADDRINUSE: address already in use :::3000\n    at Server.setupListenHandle [as _listen2] (node:net:1733:16)\n    at listenInCluster (node:net:1781:12)\n    at Server.listen (node:net:1869:7)\n    at Function.listen (C:\\FundoNote\\fundo-app\\node_modules\\express\\lib\\application.js:635:24)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\src\\/index.js:37:5)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Module._compile (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Object.newLoader [as .js] (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:922:12)\n    at Function.runMain (node:internal/modules/run_main:81:12)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\node\\src\\_babel-node.ts:223:12)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:922:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-02-16T10:54:46.392Z","trace":[{"column":16,"file":"node:net","function":"Server.setupListenHandle [as _listen2]","line":1733,"method":"setupListenHandle [as _listen2]","native":false},{"column":12,"file":"node:net","function":"listenInCluster","line":1781,"method":null,"native":false},{"column":7,"file":"node:net","function":"Server.listen","line":1869,"method":"listen","native":false},{"column":24,"file":"C:\\FundoNote\\fundo-app\\node_modules\\express\\lib\\application.js","function":"Function.listen","line":635,"method":"listen","native":false},{"column":5,"file":"C:\\FundoNote\\fundo-app\\src\\/index.js","function":null,"line":37,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1218,"method":"_compile","native":false},{"column":24,"file":"C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":136,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1272,"method":".js","native":false},{"column":7,"file":"C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":141,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1081,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":922,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.runMain","line":81,"method":"runMain","native":false},{"column":12,"file":"C:\\FundoNote\\fundo-app\\node_modules\\@babel\\node\\src\\_babel-node.ts","function":null,"line":223,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1218,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1272,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1081,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":922,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.executeUserEntryPoint [as runMain]","line":81,"method":"executeUserEntryPoint [as runMain]","native":false},{"column":47,"file":"node:internal/main/run_main_module","function":null,"line":23,"method":null,"native":false}]}
error: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1733:16)
    at listenInCluster (node:net:1781:12)
    at Server.listen (node:net:1869:7)
    at Function.listen (C:\FundoNote\fundo-app\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (C:\FundoNote\fundo-app\src\/index.js:37:5)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._compile (C:\FundoNote\fundo-app\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.newLoader [as .js] (C:\FundoNote\fundo-app\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.runMain (node:internal/modules/run_main:81:12)
    at Object.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\node\src\_babel-node.ts:223:12)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32) {"date":"Thu Feb 16 2023 16:25:18 GMT+0530 (India Standard Time)","error":{"address":"::","code":"EADDRINUSE","errno":-4091,"port":3000,"syscall":"listen"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":30343.234},"process":{"argv":["node","C:\\FundoNote\\fundo-app\\src\\index.js"],"cwd":"C:\\FundoNote\\fundo-app","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19178532,"external":20714624,"heapTotal":86769664,"heapUsed":67215328,"rss":130351104},"pid":26104,"uid":null,"version":"v18.13.0"},"stack":"Error: listen EADDRINUSE: address already in use :::3000\n    at Server.setupListenHandle [as _listen2] (node:net:1733:16)\n    at listenInCluster (node:net:1781:12)\n    at Server.listen (node:net:1869:7)\n    at Function.listen (C:\\FundoNote\\fundo-app\\node_modules\\express\\lib\\application.js:635:24)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\src\\/index.js:37:5)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Module._compile (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Object.newLoader [as .js] (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:922:12)\n    at Function.runMain (node:internal/modules/run_main:81:12)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\node\\src\\_babel-node.ts:223:12)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)","timestamp":"2023-02-16T10:55:18.313Z","trace":[{"column":16,"file":"node:net","function":"Server.setupListenHandle [as _listen2]","line":1733,"method":"setupListenHandle [as _listen2]","native":false},{"column":12,"file":"node:net","function":"listenInCluster","line":1781,"method":null,"native":false},{"column":7,"file":"node:net","function":"Server.listen","line":1869,"method":"listen","native":false},{"column":24,"file":"C:\\FundoNote\\fundo-app\\node_modules\\express\\lib\\application.js","function":"Function.listen","line":635,"method":"listen","native":false},{"column":5,"file":"C:\\FundoNote\\fundo-app\\src\\/index.js","function":null,"line":37,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1218,"method":"_compile","native":false},{"column":24,"file":"C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":136,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1272,"method":".js","native":false},{"column":7,"file":"C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":141,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1081,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":922,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.runMain","line":81,"method":"runMain","native":false},{"column":12,"file":"C:\\FundoNote\\fundo-app\\node_modules\\@babel\\node\\src\\_babel-node.ts","function":null,"line":223,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1218,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1272,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1081,"method":"load","native":false}]}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T10:55:42.483Z"}
info: Connected to the database. {"timestamp":"2023-02-16T10:55:51.531Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T11:10:58.302Z"}
info: Connected to the database. {"timestamp":"2023-02-16T11:11:09.015Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T11:17:15.382Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T11:17:28.769Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T11:17:37.466Z"}
info: Connected to the database. {"timestamp":"2023-02-16T11:17:41.598Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T11:21:41.123Z"}
info: Connected to the database. {"timestamp":"2023-02-16T11:21:46.515Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T11:24:24.558Z"}
info: Connected to the database. {"timestamp":"2023-02-16T11:24:28.953Z"}
error: 
    status - 500 
    message - ValidationError: "password" length must be at least 8 characters long 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-16T11:24:42.367Z"}
error: 
    status - 500 
    message - ValidationError: "confirmPassword" length must be at least 8 characters long 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-16T11:25:09.003Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T11:30:59.100Z"}
info: Connected to the database. {"timestamp":"2023-02-16T11:31:08.503Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T11:54:59.467Z"}
info: Connected to the database. {"timestamp":"2023-02-16T11:55:04.070Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.symbol(...).string is not a function
    at newUserValidator (C:\FundoNote\fundo-app\src\validators\/user.validator.js:7:25)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-16T11:55:07.568Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.symbol(...).string is not a function
    at newUserValidator (C:\FundoNote\fundo-app\src\validators\/user.validator.js:7:25)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-16T11:55:18.913Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T13:15:22.487Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T13:16:38.488Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T13:16:46.382Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.allow(...).min is not a function
    at newUserValidator (C:\FundoNote\fundo-app\src\validators\/user.validator.js:7:45)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-16T13:17:00.498Z"}
error: Could not connect to the database. Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/ {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/\n    at NativeConnection.Connection.openUri (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\FundoNote\\fundo-app\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12\n    at database (C:\\FundoNote\\fundo-app\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\src\\/index.js:30:9)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Module._compile (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Object.newLoader [as .js] (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:922:12)\n    at Function.runMain (node:internal/modules/run_main:81:12)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\node\\src\\_babel-node.ts:223:12)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:922:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-02-16T13:18:02.943Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T13:22:53.645Z"}
info: Connected to the database. {"timestamp":"2023-02-16T13:23:04.646Z"}
error: 
    status - 500 
    message - ReferenceError: Regex is not defined
    at newUserValidator (C:\FundoNote\fundo-app\src\validators\/user.validator.js:7:38)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-16T13:26:18.082Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T13:28:07.034Z"}
info: Connected to the database. {"timestamp":"2023-02-16T13:28:26.537Z"}
error: 
    status - 500 
    message - ValidationError: "email" must be a valid email 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-16T13:29:58.842Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T13:57:46.425Z"}
info: Connected to the database. {"timestamp":"2023-02-16T13:57:56.609Z"}
error: 
    status - 500 
    message - ValidationError: "confirmPassword" is required 
    url - /api/v1/users/user 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-16T13:58:18.804Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T13:58:39.689Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T13:58:48.543Z"}
info: Connected to the database. {"timestamp":"2023-02-16T13:58:52.532Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T14:08:21.622Z"}
info: Connected to the database. {"timestamp":"2023-02-16T14:08:25.874Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T15:45:24.316Z"}
info: Connected to the database. {"timestamp":"2023-02-16T15:45:29.683Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T15:45:34.603Z"}
info: Connected to the database. {"timestamp":"2023-02-16T15:45:38.713Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T15:45:47.625Z"}
info: Connected to the database. {"timestamp":"2023-02-16T15:45:51.153Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T15:46:12.049Z"}
info: Connected to the database. {"timestamp":"2023-02-16T15:46:17.437Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T15:47:15.468Z"}
info: Connected to the database. {"timestamp":"2023-02-16T15:47:19.616Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T15:53:34.160Z"}
info: Connected to the database. {"timestamp":"2023-02-16T15:53:43.259Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:32:46)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at getUser (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:29:21)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-16T15:55:33.399Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:32:46)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at getUser (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:29:21)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-16T15:55:45.872Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token } in JSON at position 45
    at JSON.parse (<anonymous>)
    at parse (C:\FundoNote\fundo-app\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-16T15:55:53.342Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T15:59:03.586Z"}
info: Connected to the database. {"timestamp":"2023-02-16T15:59:13.081Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:32:46)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at getUser (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:29:21)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-16T16:00:23.267Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:32:46)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at getUser (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:29:21)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-16T16:00:58.617Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T16:02:07.687Z"}
info: Connected to the database. {"timestamp":"2023-02-16T16:02:11.735Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:32:46)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at getUser (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:29:21)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-16T16:02:32.782Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T16:08:12.162Z"}
info: Connected to the database. {"timestamp":"2023-02-16T16:08:15.940Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T16:15:10.135Z"}
info: Connected to the database. {"timestamp":"2023-02-16T16:15:19.573Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T16:16:08.321Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T16:16:12.012Z"}
info: Connected to the database. {"timestamp":"2023-02-16T16:16:16.736Z"}
error: 
    status - 500 
    message - ReferenceError: body is not defined
    at _callee2$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:32:46)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at getUser (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:29:21)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-16T16:17:49.519Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T16:18:14.419Z"}
info: Connected to the database. {"timestamp":"2023-02-16T16:18:19.047Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T16:18:22.769Z"}
info: Connected to the database. {"timestamp":"2023-02-16T16:18:31.624Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T16:19:06.966Z"}
info: Connected to the database. {"timestamp":"2023-02-16T16:19:10.814Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T16:37:26.696Z"}
info: Connected to the database. {"timestamp":"2023-02-16T16:37:31.473Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-16T17:05:28.667Z"}
info: Connected to the database. {"timestamp":"2023-02-16T17:05:34.006Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is required 
    url - /api/v1/users/newuser/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-16T17:17:45.158Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T02:26:39.571Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\FundoNote\\fundo-app\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12\n    at database (C:\\FundoNote\\fundo-app\\src\\config\\/database.js:4:15)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\src\\/index.js:30:9)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Module._compile (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Object.newLoader [as .js] (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:922:12)\n    at Function.runMain (node:internal/modules/run_main:81:12)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\node\\src\\_babel-node.ts:223:12)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:922:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-02-17T02:27:09.592Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T02:28:08.909Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\FundoNote\\fundo-app\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12","timestamp":"2023-02-17T02:28:38.921Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T02:30:22.418Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\FundoNote\\fundo-app\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12","timestamp":"2023-02-17T02:30:52.430Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T02:36:45.464Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\FundoNote\\fundo-app\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12","timestamp":"2023-02-17T02:37:15.470Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:38:04.826Z"}
error: Could not connect to the database. connect ECONNREFUSED ::1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED ::1:27017\n    at NativeConnection.Connection.openUri (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:351:10\n    at C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (C:\\FundoNote\\fundo-app\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (C:\\FundoNote\\fundo-app\\src\\config\\/database.js:12:20)\n    at tryCatch (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:44:17)\n    at Generator.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:125:22)\n    at Generator.next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:69:21)\n    at asyncGeneratorStep (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:22:9)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:27:7\n    at new Promise (<anonymous>)\n    at C:\\FundoNote\\fundo-app\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:19:12","timestamp":"2023-02-17T02:38:34.849Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:40:10.576Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:40:10.593Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:47:12.626Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:47:12.641Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:49:42.984Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:49:42.998Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:50:21.797Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:50:21.813Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:50:39.588Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:50:39.602Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:51:56.734Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:51:56.757Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:53:04.358Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:53:04.385Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:55:06.217Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:55:06.231Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:57:03.242Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:57:03.256Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:57:26.848Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:57:26.863Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:59:01.285Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:59:01.300Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of null (reading 'password')
    at _callee2$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:33:49)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T02:59:06.800Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T02:59:53.985Z"}
info: Connected to the database. {"timestamp":"2023-02-17T02:59:54.004Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T03:00:19.704Z"}
info: Connected to the database. {"timestamp":"2023-02-17T03:00:19.721Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T03:00:34.292Z"}
info: Connected to the database. {"timestamp":"2023-02-17T03:00:34.307Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of null (reading 'password')
    at _callee2$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:33:49)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T03:00:47.550Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T03:01:16.525Z"}
info: Connected to the database. {"timestamp":"2023-02-17T03:01:16.540Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T03:24:26.075Z"}
info: Connected to the database. {"timestamp":"2023-02-17T03:24:26.128Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T03:42:59.784Z"}
info: Connected to the database. {"timestamp":"2023-02-17T03:42:59.834Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-17T04:01:37.255Z"}
info: Connected to the database. {"timestamp":"2023-02-17T04:01:37.273Z"}
error: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1733:16)
    at listenInCluster (node:net:1781:12)
    at Server.listen (node:net:1869:7)
    at Function.listen (C:\FundoNote\fundo-app\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (C:\FundoNote\fundo-app\src\/index.js:37:5)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._compile (C:\FundoNote\fundo-app\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.newLoader [as .js] (C:\FundoNote\fundo-app\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.runMain (node:internal/modules/run_main:81:12)
    at Object.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\node\src\_babel-node.ts:223:12)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {"date":"Fri Feb 17 2023 11:15:29 GMT+0530 (India Standard Time)","error":{"address":"::","code":"EADDRINUSE","errno":-4091,"port":3000,"syscall":"listen"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":13472.062},"process":{"argv":["node","C:\\FundoNote\\fundo-app\\src\\index.js"],"cwd":"C:\\FundoNote\\fundo-app","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19260156,"external":20795521,"heapTotal":92766208,"heapUsed":55149192,"rss":131932160},"pid":26016,"uid":null,"version":"v18.13.0"},"stack":"Error: listen EADDRINUSE: address already in use :::3000\n    at Server.setupListenHandle [as _listen2] (node:net:1733:16)\n    at listenInCluster (node:net:1781:12)\n    at Server.listen (node:net:1869:7)\n    at Function.listen (C:\\FundoNote\\fundo-app\\node_modules\\express\\lib\\application.js:635:24)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\src\\/index.js:37:5)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Module._compile (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Object.newLoader [as .js] (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:922:12)\n    at Function.runMain (node:internal/modules/run_main:81:12)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\node\\src\\_babel-node.ts:223:12)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:922:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-02-17T05:45:29.747Z","trace":[{"column":16,"file":"node:net","function":"Server.setupListenHandle [as _listen2]","line":1733,"method":"setupListenHandle [as _listen2]","native":false},{"column":12,"file":"node:net","function":"listenInCluster","line":1781,"method":null,"native":false},{"column":7,"file":"node:net","function":"Server.listen","line":1869,"method":"listen","native":false},{"column":24,"file":"C:\\FundoNote\\fundo-app\\node_modules\\express\\lib\\application.js","function":"Function.listen","line":635,"method":"listen","native":false},{"column":5,"file":"C:\\FundoNote\\fundo-app\\src\\/index.js","function":null,"line":37,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1218,"method":"_compile","native":false},{"column":24,"file":"C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":136,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1272,"method":".js","native":false},{"column":7,"file":"C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":141,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1081,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":922,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.runMain","line":81,"method":"runMain","native":false},{"column":12,"file":"C:\\FundoNote\\fundo-app\\node_modules\\@babel\\node\\src\\_babel-node.ts","function":null,"line":223,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1218,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1272,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1081,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":922,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.executeUserEntryPoint [as runMain]","line":81,"method":"executeUserEntryPoint [as runMain]","native":false},{"column":47,"file":"node:internal/main/run_main_module","function":null,"line":23,"method":null,"native":false}]}
error: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1733:16)
    at listenInCluster (node:net:1781:12)
    at Server.listen (node:net:1869:7)
    at Function.listen (C:\FundoNote\fundo-app\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (C:\FundoNote\fundo-app\src\/index.js:37:5)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._compile (C:\FundoNote\fundo-app\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.newLoader [as .js] (C:\FundoNote\fundo-app\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.runMain (node:internal/modules/run_main:81:12)
    at Object.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\node\src\_babel-node.ts:223:12)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32) {"date":"Fri Feb 17 2023 11:16:09 GMT+0530 (India Standard Time)","error":{"address":"::","code":"EADDRINUSE","errno":-4091,"port":3000,"syscall":"listen"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":13511.937},"process":{"argv":["node","C:\\FundoNote\\fundo-app\\src\\index.js"],"cwd":"C:\\FundoNote\\fundo-app","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19058035,"external":20594127,"heapTotal":86507520,"heapUsed":65158944,"rss":128520192},"pid":560,"uid":null,"version":"v18.13.0"},"stack":"Error: listen EADDRINUSE: address already in use :::3000\n    at Server.setupListenHandle [as _listen2] (node:net:1733:16)\n    at listenInCluster (node:net:1781:12)\n    at Server.listen (node:net:1869:7)\n    at Function.listen (C:\\FundoNote\\fundo-app\\node_modules\\express\\lib\\application.js:635:24)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\src\\/index.js:37:5)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Module._compile (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Object.newLoader [as .js] (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:922:12)\n    at Function.runMain (node:internal/modules/run_main:81:12)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\node\\src\\_babel-node.ts:223:12)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)","timestamp":"2023-02-17T05:46:09.615Z","trace":[{"column":16,"file":"node:net","function":"Server.setupListenHandle [as _listen2]","line":1733,"method":"setupListenHandle [as _listen2]","native":false},{"column":12,"file":"node:net","function":"listenInCluster","line":1781,"method":null,"native":false},{"column":7,"file":"node:net","function":"Server.listen","line":1869,"method":"listen","native":false},{"column":24,"file":"C:\\FundoNote\\fundo-app\\node_modules\\express\\lib\\application.js","function":"Function.listen","line":635,"method":"listen","native":false},{"column":5,"file":"C:\\FundoNote\\fundo-app\\src\\/index.js","function":null,"line":37,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1218,"method":"_compile","native":false},{"column":24,"file":"C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":136,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1272,"method":".js","native":false},{"column":7,"file":"C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":141,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1081,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":922,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.runMain","line":81,"method":"runMain","native":false},{"column":12,"file":"C:\\FundoNote\\fundo-app\\node_modules\\@babel\\node\\src\\_babel-node.ts","function":null,"line":223,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1218,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1272,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1081,"method":"load","native":false}]}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T05:46:58.839Z"}
info: Connected to the database. {"timestamp":"2023-02-17T05:46:58.872Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T05:50:14.991Z"}
info: Connected to the database. {"timestamp":"2023-02-17T05:50:15.038Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T05:50:20.150Z"}
info: Connected to the database. {"timestamp":"2023-02-17T05:50:20.166Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T05:50:25.918Z"}
info: Connected to the database. {"timestamp":"2023-02-17T05:50:25.934Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T05:50:31.827Z"}
info: Connected to the database. {"timestamp":"2023-02-17T05:50:31.841Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T05:50:37.335Z"}
info: Connected to the database. {"timestamp":"2023-02-17T05:50:37.351Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T05:50:43.078Z"}
info: Connected to the database. {"timestamp":"2023-02-17T05:50:43.093Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T05:50:48.485Z"}
info: Connected to the database. {"timestamp":"2023-02-17T05:50:48.502Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T06:04:15.638Z"}
info: Connected to the database. {"timestamp":"2023-02-17T06:04:15.655Z"}
error: 
    status - 500 
    message - ValidationError: "email" must be a valid email 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T06:05:16.330Z"}
error: 
    status - 500 
    message - ValidationError: "email" must be a valid email 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T06:05:26.675Z"}
error: 
    status - 500 
    message - ValidationError: "email" must be a valid email 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T06:05:37.354Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T06:10:03.375Z"}
info: Connected to the database. {"timestamp":"2023-02-17T06:10:03.390Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T06:14:14.820Z"}
info: Connected to the database. {"timestamp":"2023-02-17T06:14:14.835Z"}
error: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1733:16)
    at listenInCluster (node:net:1781:12)
    at Server.listen (node:net:1869:7)
    at Function.listen (C:\FundoNote\fundo-app\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (C:\FundoNote\fundo-app\src\/index.js:37:5)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._compile (C:\FundoNote\fundo-app\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.newLoader [as .js] (C:\FundoNote\fundo-app\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.runMain (node:internal/modules/run_main:81:12)
    at Object.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\node\src\_babel-node.ts:223:12)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32) {"date":"Fri Feb 17 2023 11:45:13 GMT+0530 (India Standard Time)","error":{"address":"::","code":"EADDRINUSE","errno":-4091,"port":3000,"syscall":"listen"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":15255.453},"process":{"argv":["node","C:\\FundoNote\\fundo-app\\src\\index.js"],"cwd":"C:\\FundoNote\\fundo-app","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19058035,"external":20594127,"heapTotal":86507520,"heapUsed":64992560,"rss":129220608},"pid":22964,"uid":null,"version":"v18.13.0"},"stack":"Error: listen EADDRINUSE: address already in use :::3000\n    at Server.setupListenHandle [as _listen2] (node:net:1733:16)\n    at listenInCluster (node:net:1781:12)\n    at Server.listen (node:net:1869:7)\n    at Function.listen (C:\\FundoNote\\fundo-app\\node_modules\\express\\lib\\application.js:635:24)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\src\\/index.js:37:5)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Module._compile (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Object.newLoader [as .js] (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:922:12)\n    at Function.runMain (node:internal/modules/run_main:81:12)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\node\\src\\_babel-node.ts:223:12)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)","timestamp":"2023-02-17T06:15:13.131Z","trace":[{"column":16,"file":"node:net","function":"Server.setupListenHandle [as _listen2]","line":1733,"method":"setupListenHandle [as _listen2]","native":false},{"column":12,"file":"node:net","function":"listenInCluster","line":1781,"method":null,"native":false},{"column":7,"file":"node:net","function":"Server.listen","line":1869,"method":"listen","native":false},{"column":24,"file":"C:\\FundoNote\\fundo-app\\node_modules\\express\\lib\\application.js","function":"Function.listen","line":635,"method":"listen","native":false},{"column":5,"file":"C:\\FundoNote\\fundo-app\\src\\/index.js","function":null,"line":37,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1218,"method":"_compile","native":false},{"column":24,"file":"C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":136,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1272,"method":".js","native":false},{"column":7,"file":"C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":141,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1081,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":922,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.runMain","line":81,"method":"runMain","native":false},{"column":12,"file":"C:\\FundoNote\\fundo-app\\node_modules\\@babel\\node\\src\\_babel-node.ts","function":null,"line":223,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1218,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1272,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1081,"method":"load","native":false}]}
info: Connected to the database. {"timestamp":"2023-02-17T06:15:13.167Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T06:16:27.838Z"}
info: Connected to the database. {"timestamp":"2023-02-17T06:16:27.855Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T09:40:12.195Z"}
info: Connected to the database. {"timestamp":"2023-02-17T09:40:12.251Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" must be a string 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T09:41:08.103Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T09:45:54.784Z"}
info: Connected to the database. {"timestamp":"2023-02-17T09:45:54.833Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T09:47:35.957Z"}
info: Connected to the database. {"timestamp":"2023-02-17T09:47:35.999Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" with value "ab" fails to match the required pattern: /^[a-zA-Z]{3,30}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T09:47:48.799Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" with value "ab1" fails to match the required pattern: /^[a-zA-Z]{3,30}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T09:47:59.284Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" with value "ab541" fails to match the required pattern: /^[a-zA-Z]{3,30}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T09:48:07.753Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" with value "abssssssssssssssssssssssssssssssssssss" fails to match the required pattern: /^[a-zA-Z]{3,30}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T09:48:58.837Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T09:50:46.440Z"}
info: Connected to the database. {"timestamp":"2023-02-17T09:50:46.489Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T09:56:37.567Z"}
info: Connected to the database. {"timestamp":"2023-02-17T09:56:37.606Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.string(...).minOfSpecialCharacters is not a function
    at newUserValidator (C:\FundoNote\fundo-app\src\validators\/user.validator.js:8:28)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T09:57:51.822Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.string(...).minOfSpecialCharacters is not a function
    at newUserValidator (C:\FundoNote\fundo-app\src\validators\/user.validator.js:8:28)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T09:58:26.350Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:00:07.692Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:00:07.732Z"}
error: 
    status - 500 
    message - TypeError: _joi.default.string(...).minOfSpecialCharacters is not a function
    at newUserValidator (C:\FundoNote\fundo-app\src\validators\/user.validator.js:8:28)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:00:19.841Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:07:52.883Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:07:52.912Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:09:46.761Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:09:46.776Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "12345687" fails to match the required pattern: /^[a-z]{3}-[A-Z]{1}-[0-9]{3}-[!@#$%&*]{1}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:09:54.663Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "Asdf@123" fails to match the required pattern: /^[a-z]{3}-[A-Z]{1}-[0-9]{3}-[!@#$%&*]{1}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:10:27.975Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "Asdf123@" fails to match the required pattern: /^[a-z]{3}-[A-Z]{1}-[0-9]{3}-[!@#$%&*]{1}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:11:05.762Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:11:33.756Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:11:33.774Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "Asdf123@" fails to match the required pattern: /^[a-z+]{3}-[A-Z+]{1}-[0-9+]{3}-[!@#$%&*]{1}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:11:37.020Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:14:23.589Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:14:23.605Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "Asdf123@" fails to match the required pattern: /^[a-z]{3,}-[A-Z+]{1,}-[0-9+]{3,}-[!@#$%&*]{1,}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:14:30.786Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asdfghvb" fails to match the required pattern: /^[a-z]{3,}-[A-Z+]{1,}-[0-9+]{3,}-[!@#$%&*]{1,}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:14:54.443Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:16:04.667Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:16:04.683Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asdfghvb" fails to match the required pattern: /^[a-z]{3,}-[A-Z+]{1,}-[0-9+]{3,}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:16:11.095Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "Asdf123" fails to match the required pattern: /^[a-z]{3,}-[A-Z+]{1,}-[0-9+]{3,}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:16:33.160Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:19:29.661Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:19:29.677Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "Asdf123" fails to match the required pattern: /^[a-z]{3,}-[A-Z]{1,}-[0-9]{3,}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:19:37.683Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:19:55.784Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:19:55.800Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "Asdf123" fails to match the required pattern: /^[a-z]{3}-[A-Z]{1}-[0-9]{3}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:19:58.772Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:20:31.717Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:20:31.734Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "Asdf123" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T10:20:44.202Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:21:23.270Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:21:23.286Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:22:16.107Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:22:16.124Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:22:32.108Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:22:32.128Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T10:23:28.549Z"}
info: Connected to the database. {"timestamp":"2023-02-17T10:23:28.566Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T11:13:16.118Z"}
info: Connected to the database. {"timestamp":"2023-02-17T11:13:16.134Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T11:22:26.144Z"}
info: Connected to the database. {"timestamp":"2023-02-17T11:22:26.160Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T11:24:05.366Z"}
info: Connected to the database. {"timestamp":"2023-02-17T11:24:05.383Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asderf" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T11:24:22.360Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asderdddf" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T11:24:27.523Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asderdddf1" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T11:24:35.052Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "Asderdddf1" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T11:24:41.922Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asdfgh" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T11:24:56.655Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asdfgh@" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T11:25:11.576Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asdfgh@12" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T11:25:17.922Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T11:25:45.834Z"}
info: Connected to the database. {"timestamp":"2023-02-17T11:25:45.890Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asdfg" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T11:27:30.524Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T13:33:13.202Z"}
info: Connected to the database. {"timestamp":"2023-02-17T13:33:13.227Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T13:33:41.063Z"}
info: Connected to the database. {"timestamp":"2023-02-17T13:33:41.079Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T14:03:58.592Z"}
info: Connected to the database. {"timestamp":"2023-02-17T14:03:58.663Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "qweasdzxc" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T14:04:50.855Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "qweasdzxc4" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T14:05:19.793Z"}
error: 
    status - 500 
    message - ReferenceError: userSchema is not defined
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:5:3)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.newRegistration (C:\FundoNote\fundo-app\src\services\/user.service.js:4:29)
    at _callee$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:12:36)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at newRegistration (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:10:29)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at newUserValidator (C:\FundoNote\fundo-app\src\validators\/user.validator.js:14:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T14:05:33.330Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T14:06:41.001Z"}
info: Connected to the database. {"timestamp":"2023-02-17T14:06:41.058Z"}
error: 
    status - 500 
    message - ReferenceError: userSchema is not defined
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:6:3)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.newRegistration (C:\FundoNote\fundo-app\src\services\/user.service.js:5:29)
    at _callee$ (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:12:36)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at newRegistration (C:\FundoNote\fundo-app\src\controllers\/user.controller.js:10:29)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at newUserValidator (C:\FundoNote\fundo-app\src\validators\/user.validator.js:14:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\FundoNote\fundo-app\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:175:3)
    at router (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\FundoNote\fundo-app\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\FundoNote\fundo-app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:328:13)
    at C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:346:12)
    at next (C:\FundoNote\fundo-app\node_modules\express\lib\router\index.js:280:10)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:137:5
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-17T14:06:47.475Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T14:11:38.387Z"}
info: Connected to the database. {"timestamp":"2023-02-17T14:11:38.430Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T14:13:08.909Z"}
info: Connected to the database. {"timestamp":"2023-02-17T14:13:08.985Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T14:13:40.071Z"}
info: Connected to the database. {"timestamp":"2023-02-17T14:13:40.121Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:16:23.890Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:16:23.905Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:16:55.405Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:16:55.423Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:17:55.480Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:17:55.499Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:17:59.730Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:17:59.745Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:30:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:18:22.275Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:19:36.788Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:19:36.805Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token } in JSON at position 46
    at JSON.parse (<anonymous>)
    at parse (C:\FundoNote\fundo-app\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:20:09.603Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:18:30)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:20:15.459Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected string in JSON at position 39
    at JSON.parse (<anonymous>)
    at parse (C:\FundoNote\fundo-app\node_modules\body-parser\lib\types\json.js:89:19)
    at C:\FundoNote\fundo-app\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:204:9)
    at invokeCallback (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:231:16)
    at done (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\FundoNote\fundo-app\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:513:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:20:26.499Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:21:48.657Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:21:48.674Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:22:01.642Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:23:58.101Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:25:24.791Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:25:44.215Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:25:44.233Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:25:52.485Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:31:53.947Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:31:53.962Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:31:56.168Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:33:07.063Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:33:07.079Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:33:22.850Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:36:39.221Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:36:39.235Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:33:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:36:45.548Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:40:46.277Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:40:46.295Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:30:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:41:02.827Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:43:40.120Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:43:40.137Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:47:33.968Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:47:33.985Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:48:08.668Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:48:08.686Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:29:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:48:12.004Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of null (reading 'password')
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:59)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:48:22.475Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of null (reading 'password')
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:59)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:48:35.310Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:29:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:48:41.014Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:54:37.668Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:54:37.685Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T15:55:11.115Z"}
info: Connected to the database. {"timestamp":"2023-02-17T15:55:11.133Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:31)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T15:55:26.206Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:14:45.607Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:14:45.629Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:31)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:14:48.756Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:31)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:14:55.955Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:31)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:22:57.835Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:24:36.140Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:24:36.158Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:31)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:24:39.259Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:26:42.731Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:26:42.750Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:24:31)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login/ 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:26:47.148Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:24:31)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:34:53.943Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:38:31.332Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:38:31.350Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:24:31)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:39:04.430Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:41:51.331Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:41:51.350Z"}
error: 
    status - 500 
    message - ReferenceError: req is not defined
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:27:41)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:41:56.447Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:43:21.470Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:43:21.491Z"}
error: 
    status - 500 
    message - TypeError: _user.default.getUser is not a function
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:27:33)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:43:30.881Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:43:49.666Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:43:49.688Z"}
error: 
    status - 500 
    message - TypeError: _user.default.userLogin is not a function
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:27:33)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:43:52.726Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:44:48.994Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:44:49.014Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:45:31.323Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:45:31.341Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:47:36.547Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:47:36.574Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:208:17)
    at C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (C:\FundoNote\fundo-app\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (C:\FundoNote\fundo-app\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:31)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T16:47:44.200Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T16:48:01.177Z"}
info: Connected to the database. {"timestamp":"2023-02-17T16:48:01.200Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:16:03.080Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:16:03.100Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:16:07.098Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:16:07.180Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:16:17.818Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:16:17.837Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:16:20.705Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:16:20.721Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:16:26.507Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:16:26.524Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:17:55.418Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:17:55.439Z"}
error: 
    status - 500 
    message - Error: incorrect password 
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:25:15)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T17:18:08.484Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'password')
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:62)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T17:18:17.250Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'password')
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:62)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T17:18:30.815Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:19:03.955Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:19:03.974Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:28:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T17:19:19.058Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'password')
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:21:62)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T17:19:25.541Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:20:02.160Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:20:02.177Z"}
error: 
    status - 500 
    message - Error: Invalid email
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:28:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T17:20:14.057Z"}
error: 
    status - 500 
    message - Error: incorrect password 
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:25:15)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-17T17:20:22.633Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:20:34.078Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:20:34.097Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:21:46.215Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:21:46.237Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:22:03.360Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:22:03.380Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-17T17:23:23.206Z"}
info: Connected to the database. {"timestamp":"2023-02-17T17:23:23.221Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T02:55:00.570Z"}
info: Connected to the database. {"timestamp":"2023-02-20T02:55:00.642Z"}
error: 
    status - 500 
    message - Error: incorrect password 
    at _callee2$ (C:\FundoNote\fundo-app\src\services\/user.service.js:23:15)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2023-02-20T02:55:06.926Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T05:33:43.860Z"}
info: Connected to the database. {"timestamp":"2023-02-20T05:33:43.950Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" is required 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-20T05:34:14.791Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "987654321" fails to match the required pattern: /^[a-zA-Z0-9]{8}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-20T05:36:24.167Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T05:37:12.061Z"}
info: Connected to the database. {"timestamp":"2023-02-20T05:37:12.116Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T05:38:19.103Z"}
info: Connected to the database. {"timestamp":"2023-02-20T05:38:19.182Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T05:38:47.256Z"}
info: Connected to the database. {"timestamp":"2023-02-20T05:38:47.330Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T05:39:25.023Z"}
info: Connected to the database. {"timestamp":"2023-02-20T05:39:25.096Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T05:40:13.439Z"}
info: Connected to the database. {"timestamp":"2023-02-20T05:40:13.511Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T05:41:36.619Z"}
info: Connected to the database. {"timestamp":"2023-02-20T05:41:36.712Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T05:42:15.664Z"}
info: Connected to the database. {"timestamp":"2023-02-20T05:42:15.737Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T05:43:18.956Z"}
info: Connected to the database. {"timestamp":"2023-02-20T05:43:19.276Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T05:45:55.404Z"}
info: Connected to the database. {"timestamp":"2023-02-20T05:45:55.466Z"}
error: 
    status - 500 
    message - ReferenceError: req is not defined
    at _callee$ (C:\FundoNote\fundo-app\src\services\/user.service.js:8:14)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-20T05:46:04.613Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T05:46:42.895Z"}
info: Connected to the database. {"timestamp":"2023-02-20T05:46:43.006Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T05:48:19.898Z"}
info: Connected to the database. {"timestamp":"2023-02-20T05:48:19.947Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T05:49:36.023Z"}
info: Connected to the database. {"timestamp":"2023-02-20T05:49:36.089Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T05:51:06.674Z"}
info: Connected to the database. {"timestamp":"2023-02-20T05:51:06.743Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T05:57:07.596Z"}
info: Connected to the database. {"timestamp":"2023-02-20T05:57:07.653Z"}
error: 
    status - 500 
    message - TypeError: res.status is not a function
    at _callee$ (C:\FundoNote\fundo-app\src\services\/user.service.js:20:9)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-20T05:57:14.592Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T06:00:50.248Z"}
info: Connected to the database. {"timestamp":"2023-02-20T06:00:50.431Z"}
error: 
    status - 500 
    message - ReferenceError: data is not defined
    at _callee$ (C:\FundoNote\fundo-app\src\services\/user.service.js:23:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-20T06:01:00.474Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T06:01:52.157Z"}
info: Connected to the database. {"timestamp":"2023-02-20T06:01:52.233Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T06:02:41.849Z"}
info: Connected to the database. {"timestamp":"2023-02-20T06:02:41.922Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of null (reading 'email')
    at _callee$ (C:\FundoNote\fundo-app\src\services\/user.service.js:10:10)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-20T06:03:06.116Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of null (reading 'email')
    at _callee$ (C:\FundoNote\fundo-app\src\services\/user.service.js:10:10)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-20T06:03:17.488Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T06:05:19.911Z"}
info: Connected to the database. {"timestamp":"2023-02-20T06:05:19.983Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of null (reading 'email')
    at _callee$ (C:\FundoNote\fundo-app\src\services\/user.service.js:10:10)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-20T06:05:36.967Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T06:06:54.667Z"}
info: Connected to the database. {"timestamp":"2023-02-20T06:06:54.727Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of null (reading 'email')
    at _callee$ (C:\FundoNote\fundo-app\src\services\/user.service.js:10:10)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-20T06:07:01.723Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T06:08:15.962Z"}
info: Connected to the database. {"timestamp":"2023-02-20T06:08:16.041Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of null (reading 'email')
    at _callee$ (C:\FundoNote\fundo-app\src\services\/user.service.js:11:10)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-20T06:08:22.989Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T06:12:25.991Z"}
info: Connected to the database. {"timestamp":"2023-02-20T06:12:26.058Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T06:14:09.787Z"}
info: Connected to the database. {"timestamp":"2023-02-20T06:14:09.845Z"}
error: 
    status - 500 
    message - ReferenceError: data is not defined
    at _callee$ (C:\FundoNote\fundo-app\src\services\/user.service.js:25:13)
    at tryCatch (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\FundoNote\fundo-app\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-20T06:14:26.075Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T06:15:04.509Z"}
info: Connected to the database. {"timestamp":"2023-02-20T06:15:04.586Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T06:23:37.567Z"}
info: Connected to the database. {"timestamp":"2023-02-20T06:23:37.675Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-20T06:31:23.939Z"}
info: Connected to the database. {"timestamp":"2023-02-20T06:31:24.201Z"}
error: uncaughtException: listen EADDRINUSE: address already in use :::5000
Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (node:net:1733:16)
    at listenInCluster (node:net:1781:12)
    at Server.listen (node:net:1869:7)
    at Function.listen (C:\FundoNote\fundo-app\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (C:\FundoNote\fundo-app\src\/index.js:37:5)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._compile (C:\FundoNote\fundo-app\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.newLoader [as .js] (C:\FundoNote\fundo-app\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.runMain (node:internal/modules/run_main:81:12)
    at Object.<anonymous> (C:\FundoNote\fundo-app\node_modules\@babel\node\src\_babel-node.ts:223:12)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {"date":"Mon Feb 20 2023 14:15:04 GMT+0530 (India Standard Time)","error":{"address":"::","code":"EADDRINUSE","errno":-4091,"port":5000,"syscall":"listen"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":21385.531},"process":{"argv":["node","C:\\FundoNote\\fundo-app\\src\\index.js"],"cwd":"C:\\FundoNote\\fundo-app","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19153201,"external":20688566,"heapTotal":91893760,"heapUsed":55981968,"rss":130846720},"pid":3140,"uid":null,"version":"v18.13.0"},"stack":"Error: listen EADDRINUSE: address already in use :::5000\n    at Server.setupListenHandle [as _listen2] (node:net:1733:16)\n    at listenInCluster (node:net:1781:12)\n    at Server.listen (node:net:1869:7)\n    at Function.listen (C:\\FundoNote\\fundo-app\\node_modules\\express\\lib\\application.js:635:24)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\src\\/index.js:37:5)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Module._compile (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:136:24)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Object.newLoader [as .js] (C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js:141:7)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:922:12)\n    at Function.runMain (node:internal/modules/run_main:81:12)\n    at Object.<anonymous> (C:\\FundoNote\\fundo-app\\node_modules\\@babel\\node\\src\\_babel-node.ts:223:12)\n    at Module._compile (node:internal/modules/cjs/loader:1218:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)\n    at Module.load (node:internal/modules/cjs/loader:1081:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:922:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:23:47","timestamp":"2023-02-20T08:45:04.798Z","trace":[{"column":16,"file":"node:net","function":"Server.setupListenHandle [as _listen2]","line":1733,"method":"setupListenHandle [as _listen2]","native":false},{"column":12,"file":"node:net","function":"listenInCluster","line":1781,"method":null,"native":false},{"column":7,"file":"node:net","function":"Server.listen","line":1869,"method":"listen","native":false},{"column":24,"file":"C:\\FundoNote\\fundo-app\\node_modules\\express\\lib\\application.js","function":"Function.listen","line":635,"method":"listen","native":false},{"column":5,"file":"C:\\FundoNote\\fundo-app\\src\\/index.js","function":null,"line":37,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1218,"method":"_compile","native":false},{"column":24,"file":"C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js","function":"Module._compile","line":136,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1272,"method":".js","native":false},{"column":7,"file":"C:\\FundoNote\\fundo-app\\node_modules\\pirates\\lib\\index.js","function":"Object.newLoader [as .js]","line":141,"method":"js]","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1081,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":922,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.runMain","line":81,"method":"runMain","native":false},{"column":12,"file":"C:\\FundoNote\\fundo-app\\node_modules\\@babel\\node\\src\\_babel-node.ts","function":null,"line":223,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1218,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1272,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1081,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":922,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.executeUserEntryPoint [as runMain]","line":81,"method":"executeUserEntryPoint [as runMain]","native":false},{"column":47,"file":"node:internal/main/run_main_module","function":null,"line":23,"method":null,"native":false}]}
info: Connected to the database. {"timestamp":"2023-02-20T08:45:04.858Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T08:46:29.367Z"}
info: Connected to the database. {"timestamp":"2023-02-20T08:46:29.413Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T08:50:44.428Z"}
info: Connected to the database. {"timestamp":"2023-02-20T08:50:44.472Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T08:52:22.391Z"}
info: Connected to the database. {"timestamp":"2023-02-20T08:52:22.461Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T08:55:17.914Z"}
info: Connected to the database. {"timestamp":"2023-02-20T08:55:17.960Z"}
error: 
    status - 500 
    message - ValidationError: "firstName" with value "manju" fails to match the required pattern: /^[A-Z]{1,1}[a-z]{3,30}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-20T08:55:34.938Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T08:56:17.020Z"}
info: Connected to the database. {"timestamp":"2023-02-20T08:56:17.075Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T08:57:54.828Z"}
info: Connected to the database. {"timestamp":"2023-02-20T08:57:54.873Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T08:58:12.595Z"}
info: Connected to the database. {"timestamp":"2023-02-20T08:58:12.644Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T09:00:25.732Z"}
info: Connected to the database. {"timestamp":"2023-02-20T09:00:25.760Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T09:00:52.596Z"}
info: Connected to the database. {"timestamp":"2023-02-20T09:00:52.645Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T09:01:01.717Z"}
info: Connected to the database. {"timestamp":"2023-02-20T09:01:01.755Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T09:08:12.334Z"}
info: Connected to the database. {"timestamp":"2023-02-20T09:08:12.389Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T09:08:39.798Z"}
info: Connected to the database. {"timestamp":"2023-02-20T09:08:39.857Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "98765432" fails to match the required pattern: /^[a-z]{1,8}[A-Z]{1,1}[0-9]{1,2}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-20T09:08:58.132Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asdA9876543" fails to match the required pattern: /^[a-z]{1,8}[A-Z]{1,1}[0-9]{1,2}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-20T09:09:14.112Z"}
error: 
    status - 500 
    message - ValidationError: "password" with value "asdA98765" fails to match the required pattern: /^[a-z]{1,8}[A-Z]{1,1}[0-9]{1,2}$/ 
    url - /api/v1/users/ 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-20T09:09:22.239Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T09:10:14.024Z"}
info: Connected to the database. {"timestamp":"2023-02-20T09:10:14.076Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T09:11:46.956Z"}
info: Connected to the database. {"timestamp":"2023-02-20T09:11:47.140Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T09:13:24.672Z"}
info: Connected to the database. {"timestamp":"2023-02-20T09:13:24.722Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T09:13:56.076Z"}
info: Connected to the database. {"timestamp":"2023-02-20T09:13:56.155Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T09:15:26.922Z"}
info: Connected to the database. {"timestamp":"2023-02-20T09:15:26.965Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T09:16:37.889Z"}
info: Connected to the database. {"timestamp":"2023-02-20T09:16:37.950Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T09:16:57.774Z"}
info: Connected to the database. {"timestamp":"2023-02-20T09:16:57.821Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T09:17:48.146Z"}
info: Connected to the database. {"timestamp":"2023-02-20T09:17:48.191Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T09:20:17.577Z"}
info: Connected to the database. {"timestamp":"2023-02-20T09:20:17.945Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2023-02-20T09:22:03.490Z"}
info: Connected to the database. {"timestamp":"2023-02-20T09:22:03.534Z"}
